name: dfast_qc
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python>=3.7
  - mash
  - skani
  - hmmer
  - prodigal
  - pip:
    - checkm-genome
    - ete3
    - more-itertools
    - peewee