name: test
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python>=3.7
  - mash
  - skani
  - gsl==2.5
  - pip:
    - checkm-genome==1.2.2
    - ete3
    - more-itertools
    - peewee