name: dfast_qc
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python>=3.7
  - fastani=1.32
  - hmmer
  - prodigal
  - blast
  - pip:
    - checkm-genome==1.2.2
    - ete3
    - more-itertools
    - peewee
